version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - NEXT_PUBLIC_ALLOW_BROWSER=false
      - NEXT_PUBLIC_MAX_RETRIES=3
      - NEXT_PUBLIC_API_TIMEOUT=30000
    env_file:
      - .env.local
