version: '3.8'

services:
  ai-artifact:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - NEXT_PUBLIC_USE_CLAUDE_API=true
      - NEXT_PUBLIC_AGENT_MODE=production
      - NEXT_PUBLIC_API_TIMEOUT=30000
      - NEXT_PUBLIC_MAX_RETRIES=3
      - NEXT_PUBLIC_ALLOW_BROWSER=false
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run build && npm start
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
